language: python

python:
  - "2.7"
  - "3.4"

script:
  - python hello.py
  - python hellocody.py
  - python hellotaylor.py
  - python hellojeanmichel.py
  - python hellogarrett.py
  - sh test.sh

#before_install:
# - pip install coverage
# - cd python

#script:
# - nosetests -v --with-coverage
