language: cpp

before_install:
  - wget https://googletest.googlecode.com/files/gtest-1.7.0.zip
  - unzip gtest-1.7.0.zip 
  - cd gtest-1.7.0/
  - ./configure --prefix=$TRAVIS_BUILD_DIR --with-pthreads=no
  - make
  - mkdir $TRAVIS_BUILD_DIR/include/
  - cp -r include/gtest $TRAVIS_BUILD_DIR/include
  - mkdir $TRAVIS_BUILD_DIR/lib/
  - cp lib/.libs/* $TRAVIS_BUILD_DIR/lib/
  - cd ..
  - export CPLUS_INCLUDE_PATH=$TRAVIS_BUILD_DIR/include:$CPLUS_INCLUDE_PATH
  - export LIBRARY_PATH=$TRAVIS_BUILD_DIR/lib:$LIBRARY_PATH
  - export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/lib:$LD_LIBRARY_PATH
  - cd cpp

script:
  - make googletest
