language: python

python: 
- "2.7"
- "3.4"

script:
- python helloworld.py
- python helloIsaacBondoc.py
- python helloElliotWhite.py
- python helloJamesLopez.py
- sh test.sh

 #before_install:
 # - pip install coverage
 #  - cd python

 #script:
 #  - nosetests -v --with-coverage
